export enum Region {
    "Ariana",
    'Ben Arous',
    'Tunis' ,
    'Manouba',
    'Sfax' ,
    'Béja' ,
    'Bizerte',
    'Gabes',
    'Gafsa',
    'Jendouba',
    'Kairaouan',
    'Kasserine',
    'Kébili',
    'Le Kef',
    'Mahdia',
    'Médenine' ,
    'Monastir' ,
    'Nabeul',
    'Sidi Bouzid' ,
    'Siliana',
    'Sousse',
    'Tataouine',
    'Tozeur',
    'Zaghouan'
  }
  